# Generated by Django 4.2.7 on 2024-01-12 12:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='1@1.1', max_length=15, unique=True, verbose_name='email')),
                ('full_name', models.TextField(max_length=100, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='тема')),
                ('body', models.TextField(max_length=500, verbose_name='сообщение')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='дата и время старта')),
                ('period', models.CharField(choices=[('1', 'ones a day'), ('2', 'ones a week'), ('3', 'ones a month')], default='3', max_length=1, verbose_name='периодичность')),
                ('client', models.ManyToManyField(to='mailing.client')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message')),
            ],
        ),
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(verbose_name='дата и время отправки')),
                ('status', models.CharField(choices=[('1', 'sent'), ('2', 'error')], default='1', max_length=1, verbose_name='статус')),
                ('server_answer', models.TextField(blank=True, verbose_name='ответ сервера')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.client')),
                ('settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.settings')),
            ],
        ),
    ]
