# Generated by Django 4.2.7 on 2023-12-06 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='тема')),
                ('content', models.TextField(verbose_name='содержание')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название рассылки')),
                ('start_date', models.DateTimeField(verbose_name='время старта рассылки')),
                ('next_date', models.DateTimeField(default=models.DateTimeField(verbose_name='время старта рассылки'), verbose_name='время следующей рассылки')),
                ('end_date', models.DateTimeField(verbose_name='время окончания рассылки')),
                ('interval', models.CharField(choices=[('ежедневно', 'ежедневно'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц')], max_length=50, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('Создана', 'Создана'), ('Активна', 'Активна'), ('Завершена', 'Завершена')], help_text='Выберите Создана или Завершена', max_length=50)),
                ('mail_to', models.ManyToManyField(to='sendmail.client', verbose_name='кому')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sendmail.message', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mailing_time', models.DateTimeField(auto_now=True, verbose_name='время последней рассылки')),
                ('status', models.CharField(max_length=50, null=True, verbose_name='статус попытки')),
                ('response', models.TextField(default=None, null=True, verbose_name='ответ сервера')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sendmail.message', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
            },
        ),
    ]
