# Generated by Django 4.2.7 on 2023-12-06 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0002_alter_mailing_next_date_alter_mailing_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='next_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время следующей рассылки'),
        ),
    ]
