# Generated by Django 4.2.7 on 2023-12-07 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0005_mailing_is_active_mailing_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='is_active',
            new_name='is_activated',
        ),
    ]
