# Generated by Django 4.2.7 on 2023-12-07 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0006_rename_is_active_mailing_is_activated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('start_date',), 'permissions': [('set_is_activated', 'Может отключать рассылку')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
