# Generated by Django 4.2.7 on 2023-12-10 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0008_message_owner_alter_mailing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sendmail.mailing', verbose_name='рассылка'),
        ),
    ]
