# Generated by Django 4.2.7 on 2023-12-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0009_logs_mailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='response',
        ),
    ]
