# Generated by Django 4.2.7 on 2023-12-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0012_client_owner_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='interval',
            field=models.CharField(choices=[('разовая', 'разовая'), ('ежедневно', 'ежедневно'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц')], default='разовая', max_length=50, verbose_name='периодичность'),
        ),
    ]
