# Generated by Django 4.2.7 on 2024-01-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0013_alter_mailing_interval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(max_length=125, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='last_mailing_time',
            field=models.DateTimeField(auto_now=True, verbose_name='время последней отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='interval',
            field=models.CharField(choices=[('Разовая', 'Разовая'), ('Ежедневно', 'Ежедневно'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='разовая', max_length=50, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запушена'), ('Завершена', 'Завершена')], help_text='Выберите создана или Завершена', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='содержимое'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=100, verbose_name='тема'),
        ),
    ]
